Repository codestates-seb/seb44_main_034, pull requests merged in 2023-07, with the labels that each got.

#71 ESLint 및 Prettier 패키지 설치 및 ESLint 설정파일 설정
  client/.eslintrc.cjs
  client/package-lock.json
  client/package.json
  client/src/App.tsx
Labels: 설정, 🌝 FE

#74 feat: 어플리케이션 설정
  server/cafeIn/src/main/resources/application-dev.yml
Labels: 🌚 BE

#77 Be dev
  server/cafeIn/appspec.yml
  server/cafeIn/buildspec.yml
  server/cafeIn/scripts/initialize.sh
  server/cafeIn/scripts/server_clear.sh
  server/cafeIn/scripts/server_start.sh
  server/cafeIn/scripts/server_stop.sh
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/controller/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/dto/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/entity/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/repository/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/service/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/member/controller/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/member/dto/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/member/entity/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/member/repository/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/member/service/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/controller/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/dto/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/entity/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/repository/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/service/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/owner/controller/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/owner/dto/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/owner/entity/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/owner/repository/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/owner/service/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/base/BaseEntity.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/config/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/exception/CustomException.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/exception/ErrorCode.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/exception/ErrorResponse.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/exception/GlobalExceptionHandler.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/response/ApplicationResponse.java
  server/cafeIn/src/main/resources/application-dev.yml
Labels: 기능, 🌚 BE

#80 feat: 배포 파일 추가
  server/cafeIn/appspec.yml
  server/cafeIn/buildspec.yml
  server/cafeIn/scripts/initialize.sh
  server/cafeIn/scripts/server_clear.sh
  server/cafeIn/scripts/server_start.sh
  server/cafeIn/scripts/server_stop.sh
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/controller/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/dto/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/entity/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/repository/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/service/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/member/controller/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/member/dto/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/member/entity/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/member/repository/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/member/service/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/controller/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/dto/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/entity/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/repository/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/service/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/owner/controller/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/owner/dto/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/owner/entity/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/owner/repository/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/owner/service/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/base/BaseEntity.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/config/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/exception/CustomException.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/exception/ErrorCode.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/exception/ErrorResponse.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/exception/GlobalExceptionHandler.java
  server/cafeIn/src/main/java/mainproject/cafeIn/global/response/ApplicationResponse.java
  server/cafeIn/src/main/resources/application-dev.yml
Labels: 기능, 🌚 BE

#86 Cafe Entity 및 CRUD 개발
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/🐛-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  client/.eslintrc.cjs
  client/.gitignore
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/common/common.tsx
  client/src/components/components.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/pages/pages.tsx
  client/src/recoil/recoil.tsx
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  server/cafeIn/build.gradle
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/controller/CafeController.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/controller/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/dto/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/dto/request/CafeInfoRequest.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/dto/request/PageCafeRequest.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/dto/request/SearchCafeFilterCondition.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/dto/response/CafeDetailResponse.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/dto/response/CafeResponse.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/dto/response/GetCafeDetailResponse.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/dto/response/GetCafesResponse.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/entity/Cafe.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/entity/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/repository/CafeRepository.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/repository/CafeRepositoryCustom.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/repository/d.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/repository/implementation/CafeRepositoryImpl.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/service/CafeService.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/service/d.java
Labels: 기능, 🌚 BE

#85 카페 리스트 UI, 카페 작성 UI
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/common/button/button.tsx
  client/src/common/posting/PostThumbnail.tsx
  client/src/common/posting/plusBtn.tsx
  client/src/common/tagName.ts
  client/src/common/tags/FacilitiesTag.tsx
  client/src/common/tags/MoodTag.tsx
  client/src/components/cafe/CafeInfo.tsx
  client/src/components/header/Header.tsx
  client/src/components/post/PostHead.tsx
  client/src/components/post/PostList.tsx
  client/src/components/post/PostMood.tsx
  client/src/index.css
  client/src/mockData/cafePost.json
  client/src/pages/AddCafeInfoPage.tsx
  client/src/pages/AllPostPage.tsx
  client/src/pages/CreatePostPage.tsx
  client/src/pages/PostPage.tsx
  client/src/pages/pages.tsx
  client/src/types/type.ts
Labels: 기능, 🌝 FE, UI

#88 MenuComment Entity 및 CRUD 개발
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menucomment/controller/MenuCommentController.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menucomment/dto/request/MenuCommentRequest.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menucomment/entity/MenuComment.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menucomment/repository/MenuCommentRepository.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menucomment/repository/MenuCommentRepositoryCustom.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menucomment/repository/implementation/MenuCommentRepositoryImpl.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menucomment/service/MenuCommentService.java
Labels: 기능, 🌚 BE

#108 ✨ feat: menucomment response query 작성
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/dto/request/CafeInfoRequest.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/dto/response/GetCafesResponse.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/cafe/entity/Cafe.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/member/service/MemberService.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/dto/response/GetMenuDetailResponse.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menucomment/repository/MenuCommentRepositoryCustom.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menucomment/repository/implementation/MenuCommentRepositoryImpl.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menucomment/service/MenuCommentService.java
Labels: 기능, 🌚 BE

#109 Menu Entity 수정, response query 작성
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/controller/MenuController.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/dto/request/MenuRequest.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/dto/response/GetMenusResponse.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/dto/response/MenuResponse.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/entity/Menu.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/repository/MenuRepositoryCustom.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/repository/implementation/MenuRepositoryImpl.java
  server/cafeIn/src/main/java/mainproject/cafeIn/domain/menu/service/MenuService.java
Labels: 기능, 리팩토링, 🌚 BE

#110 fix:header,nav
  client/src/App.css
  client/src/App.tsx
  client/src/components/editusermypagebox/EditUserMyPageBox.tsx
  client/src/components/header/Header.tsx
  client/src/components/nav/Nav.tsx
  client/src/components/profilemodal/ProfileModal.tsx
  client/src/pages/Main.tsx
Labels: 🌝 FE, UI

#168 fix:following
  .DS_Store
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/postApi.tsx
  client/src/common/baseURL.tsx
  client/src/components/cafefollowermodal/CafeFollowerModal.tsx
  client/src/components/deleteaccoutbox/DeleteAccoutBox.tsx
  client/src/components/followermodal/FollowerModal.tsx
  client/src/components/followingmodal/FollowingModal.tsx
  client/src/components/header/Header.tsx
  client/src/components/loginbox/LoginBox.tsx
  client/src/components/modal/CafeFollowerModal.tsx
  client/src/components/modal/FollowerModal.tsx
  client/src/components/modal/FollowingModal.tsx
  client/src/components/modal/ProfileModal.tsx
  client/src/components/nav/Nav.tsx
  client/src/components/otheruserpagebox/OtherUserPageBox.tsx
  client/src/components/owners/EditOwnerMyPageBox.tsx
  client/src/components/owners/OwnerMyPageBox.tsx
  client/src/components/owners/OwnerSignupBox.tsx
  client/src/components/post/postItemHead.tsx
  client/src/components/users/EditUserMyPageBox.tsx
  client/src/components/users/UserMyPageBox.tsx
  client/src/components/users/UserSignupBox.tsx
  client/src/mockData/follower.json
  client/src/pages/AllPostsPage.tsx
  client/src/pages/CafePage.tsx
  client/src/pages/CreatePostPage.tsx
  client/src/pages/EditOwnerMyPage.tsx
  client/src/pages/EditPostPage.tsx
  client/src/pages/EditUserMyPage.tsx
  client/src/pages/OwnerMyPage.tsx
  client/src/pages/OwnerSignup.tsx
  client/src/pages/PostPage.tsx
  client/src/pages/UserMyPage.tsx
  client/src/pages/UserSignup.tsx
Labels: 기능, 🌝 FE, UI

#198 Fe:feat/agreementpage
  client/src/App.tsx
  client/src/assets/coffeebean.svg
  client/src/assets/coffeeshop2.jpeg
  client/src/assets/coffeeshop3.jpeg
  client/src/assets/espresso.svg
  client/src/assets/greenbean.svg
  client/src/common/baseURL.tsx
  client/src/components/deleteaccoutbox/DeleteAccoutBox.tsx
  client/src/components/modal/FollowerModal.tsx
  client/src/components/modal/FollowingModal.tsx
  client/src/components/modal/ProfileModal.tsx
  client/src/components/nav/Nav.tsx
  client/src/components/otheruser/OtherUserPageBox.tsx
  client/src/components/otheruser/UserPost.tsx
  client/src/components/owners/OwnerMyPageBox.tsx
  client/src/components/owners/OwnerSignupBox.tsx
  client/src/components/starRating.tsx
  client/src/components/users/BookmarkCafe.tsx
  client/src/components/users/BookmarkPost.tsx
  client/src/components/users/MyPost.tsx
  client/src/components/users/UserMyPageBox.tsx
  client/src/components/users/UserSignupBox.tsx
  client/src/pages/OtherUserMyPage.tsx
  client/src/pages/SignupAgreement.tsx
Labels: 기능, 🌝 FE, UI

#199 [Fe] 댓글 기능 구현
  client/db.json
  client/src/api/postApi.tsx
  client/src/common/baseURL.tsx
  client/src/common/post/PlusButton.tsx
  client/src/common/post/PostThumbnail.tsx
  client/src/components/comments/Comments.tsx
  client/src/components/comments/CommentsPagination.tsx
  client/src/components/post/PostHead.tsx
  client/src/components/post/PostList.tsx
  client/src/components/post/PostMood.tsx
  client/src/components/post/postItemHead.tsx
  client/src/mockData/comments.json
  client/src/pages/AllPostsPage.tsx
  client/src/pages/CreatePostPage.tsx
  client/src/pages/EditPostPage.tsx
  client/src/pages/Main.tsx
  client/src/pages/PostPage.tsx
  client/src/recoil/postState.tsx
  client/src/types/type.ts
Labels: 기능, 리팩토링, 🌝 FE, UI

#238 feat:main 일부
  client/src/common/baseURL.tsx
  client/src/components/cafe/CafeDetailMenu.tsx
  client/src/components/cafe/EditCafeInfo.tsx
  client/src/components/header/Header.tsx
  client/src/components/main/FilterSearchBox.tsx
  client/src/components/main/LocationBox.tsx
  client/src/components/main/SearchBox.tsx
  client/src/components/nav/Nav.tsx
  client/src/components/owners/OwnerMyPageBox.tsx
  client/src/components/owners/OwnerSignupBox.tsx
  client/src/components/users/UserMyPageBox.tsx
  client/src/components/users/UserSignupBox.tsx
  client/src/pages/EditMenuCafePage.tsx
  client/src/pages/Main.tsx
Labels: 🌝 FE, UI

#260 [Fe] feat/mainpage 4
  client/package-lock.json
  client/package.json
  client/src/Paging.css
  client/src/components/main/Cafe.tsx
  client/src/components/main/CafeList.tsx
  client/src/components/main/Pagenation.tsx
  client/src/components/modal/CafeFollowerModal.tsx
  client/src/components/otheruser/OtherUserPageBox.tsx
  client/src/components/owners/EditOwnerMyPageBox.tsx
  client/src/components/owners/OwnerMyPageBox.tsx
  client/src/pages/Main.tsx
Labels: 🌝 FE, UI

#327 [Fe] 검색 기능
  client/src/App.tsx
  client/src/api/mainApi.tsx
  client/src/api/postApi.tsx
  client/src/common/post/PostThumbnail.tsx
  client/src/common/tagNames.ts
  client/src/common/tags/FacilitiesTag.tsx
  client/src/common/tags/MoodTag.tsx
  client/src/components/comments/CommentItem.tsx
  client/src/components/comments/Comments.tsx
  client/src/components/main/FilterSearchBox.tsx
  client/src/components/main/LocationBox.tsx
  client/src/components/main/SearchBox.tsx
  client/src/components/post/PostList.tsx
  client/src/components/post/PostMood.tsx
  client/src/components/post/postItemHead.tsx
  client/src/pages/AllPostsPage.tsx
  client/src/pages/CafePage.tsx
  client/src/pages/EditPostPage.tsx
  client/src/pages/Main.tsx
  client/src/pages/PostPage.tsx
  client/src/recoil/mainState.tsx
  client/src/recoil/postState.tsx
  client/src/types/type.ts
Labels: 기능, 리팩토링, 🌝 FE, UI

#425 Fe feat/mainpage8
  client/package-lock.json
  client/package.json
  client/src/api/mainApi.tsx
  client/src/assets/iphone14.png
  client/src/components/deleteaccoutbox/DeleteAccoutBox.tsx
  client/src/components/loginbox/LoginBox.tsx
  client/src/components/main/Cafe.tsx
  client/src/components/modal/CafeFollowerModal.tsx
  client/src/components/modal/FollowerModal.tsx
  client/src/components/modal/FollowingModal.tsx
  client/src/components/modal/ProfileModal.tsx
  client/src/components/otheruser/OtherUserPageBox.tsx
  client/src/components/otheruser/UserPost.tsx
  client/src/components/owners/OwnerMyPageBox.tsx
  client/src/components/owners/OwnerSignupBox.tsx
  client/src/components/users/BookmarkCafe.tsx
  client/src/components/users/BookmarkPost.tsx
  client/src/components/users/EditUserMyPageBox.tsx
  client/src/components/users/MyPost.tsx
  client/src/components/users/UserMyPageBox.tsx
  client/src/pages/Main.tsx
  client/src/pages/OtherUserMyPage.tsx
  client/src/pages/OwnerMyPage.tsx
  client/src/pages/OwnerSignup.tsx
  client/src/pages/SignupSelect.tsx
  client/src/pages/StartPage.tsx
  client/src/pages/UserMyPage.tsx
  client/src/pages/UserSignup.tsx
Labels: 기능, 🌝 FE, UI

#426 [fe] feat/mainpage9
  client/src/assets/coffeebean.svg
  client/src/assets/roastedbean.svg
  client/src/components/googleoauth/GoogleOauth.tsx
  client/src/components/loginbox/LoginBox.tsx
  client/src/components/modal/CafeFollowerModal.tsx
  client/src/components/otheruser/OtherUserPageBox.tsx
  client/src/components/owners/EditOwnerMyPageBox.tsx
  client/src/components/owners/OwnerMyPageBox.tsx
  client/src/components/users/UserMyPageBox.tsx
Labels: 기능, 🌝 FE, UI

#438 feat Oauth Loading
  client/index.html
  client/src/App.tsx
  client/src/api/mainApi.tsx
  client/src/components/googleoauth/GoogleOauth.tsx
  client/src/components/users/UserSignupBox.tsx
  client/src/pages/Main.tsx
  client/src/pages/OauthLoading.tsx
Labels: 기능, 🌝 FE, UI

#453 Fe feat/membertest
  client/src/components/otheruser/OtherUserPageBox.tsx
  client/src/components/users/MyPost.tsx
  client/src/pages/OauthLoading.tsx
Labels: 🌝 FE

#459 [Fe] feat/oauth3
  client/src/components/modal/FollowerModal.tsx
  client/src/components/modal/FollowingModal.tsx
  client/src/pages/OauthLoading.tsx
Labels: 🌝 FE

#472 Fe feat/topscroll2
  client/src/App.tsx
  client/src/components/ScrollToTop.tsx
  client/src/components/loginbox/LoginBox.tsx
  client/src/components/users/MyPost.tsx
  client/src/pages/CreatePostPage.tsx
  client/src/pages/OauthLoading.tsx
Labels: 🌝 FE
